<?xml version='1.0' encoding='UTF-8'?><!-- Published by JAX-WS RI at http://jax-ws.dev.java.net. RI's version is Metro/2.1 (branches/2.1-6728; 2011-02-03T14:14:58+0000) JAXWS-RI/2.2.3 JAXWS/2.2. --><wsdl:definitions xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://tempuri.org/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" targetNamespace="http://tempuri.org/">
  <wsdl:types>
    <xs:schema>
      <xs:import namespace="http://tempuri.org/" schemaLocation="http://cs08.cs.sjsu.edu:9400/soap11/Student_Info?xsd=1" />
    </xs:schema>
  </wsdl:types>
  <wsdl:message name="Student_InfoOutput">
    <wsdl:part name="parameters" element="tns:Student_InfoResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="Student_InfoInput">
    <wsdl:part name="parameters" element="tns:Student_Info">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="Student_InfoPortType">
    <wsdl:operation name="Student_Info">
      <wsdl:input message="tns:Student_InfoInput">
    </wsdl:input>
      <wsdl:output message="tns:Student_InfoOutput">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="Student_InfoBinding" type="tns:Student_InfoPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
      <wsp:PolicyReference URI="#/policy/security/system/Http-Basic-Authentication.xml" />
    <wsdl:operation name="Student_Info">
      <wsdl:input>
        <soap:body parts="parameters" use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body parts="parameters" use="literal" />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="Student_Info">
    <wsdl:port name="Student_InfoPort" binding="tns:Student_InfoBinding">
      <soap:address location="http://cs08.cs.sjsu.edu:9400/soap11/Student_Info" />
    </wsdl:port>
  </wsdl:service>
    <wsp:Policy xmlns:composite="http://www.compositesw.com/ws-securitypolicy" xmlns:ns1="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:sp="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" ns1:Id="/policy/security/system/Http-Basic-Authentication.xml">
  <sp:SupportingTokens />
  <composite:HttpToken>
    <composite:HttpBasicAuthentication />
  </composite:HttpToken>
</wsp:Policy>
</wsdl:definitions>